[package]
name = "codecrafters-redis"
version = "0.1.0"
authors = ["sinxzh", "Codecrafters <hello@codecrafters.io>"]
edition = "2024"

[dependencies]
anyhow = "1.0.59"                                   # error handling
clap = { version = "4.5.41", features = ["derive"] }
